In [126]:
# 1 Importar librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from pandas import DataFrame
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import RobustScaler
from sklearn.metrics import confusion_matrix, recall_score, f1_score, precision_score

In [148]:
df = pd.read_csv("accident.csv")
df

     age  gender  speed helmet seatbelt  survived
0     18  Female     20     No      Yes         1
1     28    Male     20    Yes       No         1
2     52    Male     20    Yes       No         1
3     52  Female     20     No       No         1
4     37  Female     21     No       No         1
..   ...     ...    ...    ...      ...       ...
195   50  Female    118    Yes      Yes         0
196   59  Female    118    Yes       No         0
197   67  Female    118    Yes       No         0
198   24  Female    119    Yes      Yes         0
199   62  Female    119    Yes      Yes         0

[200 rows x 6 columns]

In [149]:
print(df['helmet'].value_counts())
df['helmet']=df['helmet'].factorize()[0]
df['helmet'].value_counts()

helmet
Yes    111
No      89
Name: count, dtype: int64

helmet
1    111
0     89
Name: count, dtype: int64

In [150]:
print(df['seatbelt'].value_counts())
df['seatbelt']=df['seatbelt'].factorize()[0]
df['seatbelt'].value_counts()

seatbelt
Yes    111
No      89
Name: count, dtype: int64

seatbelt
0    111
1     89
Name: count, dtype: int64

In [151]:
print(df['gender'].value_counts())
df['gender']=df['gender'].factorize()[0]
df['gender'].value_counts()

gender
Female    110
Male       90
Name: count, dtype: int64

gender
0    110
1     90
Name: count, dtype: int64

In [152]:
df = pd.read_csv("accident.csv")
X = df.drop(['survived'], axis=1)
y = df['survived']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40, stratify=y)

In [153]:
from sklearn.ensemble import RandomForestClassifier

# Convert categorical features to numerical using factorize
X_train['gender'] = X_train['gender'].factorize()[0]
X_test['gender'] = X_test['gender'].factorize()[0]
X_train['helmet'] = X_train['helmet'].factorize()[0]
X_test['helmet'] = X_test['helmet'].factorize()[0]
X_train['seatbelt'] = X_train['seatbelt'].factorize()[0]
X_test['seatbelt'] = X_test['seatbelt'].factorize()[0]

clf_rnd = RandomForestClassifier(n_estimators=100,random_state=42)
clf_rnd.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [154]:
y_pred = clf_rnd.predict(X_test)
f1_score (y_test, y_pred, average='weighted')

0.7480818414322251

In [141]:
df = pd.read_csv("malware2.csv")
df

,duration,total_fpackets,total_bpackets,total_fpktl,total_bpktl,min_fpktl,min_bpktl,max_fpktl,max_bpktl,mean_fpktl,...,mean_idle,max_idle,std_idle,FFNEPD,Init_Win_bytes_forward,Init_Win_bytes_backward,RRT_samples_clnt,Act_data_pkt_forward,min_seg_size_forward,class
0,823964,4,5,1172,977,52,52,748,761,293.000000,...,0.0,-1,0.0,2,4194240,370688,3,4,32,benign
1,7711002,2,0,166,0,83,-1,83,-1,83.000000,...,7711002.0,7711002,0.0,3,107008,-1,0,2,32,benign
2,0,1,0,356,0,356,-1,356,-1,356.000000,...,0.0,-1,0.0,2,0,-1,0,1,0,benign
3,369379,2,0,116,0,52,-1,64,-1,58.000000,...,0.0,-1,0.0,3,101440,-1,0,2,32,adware
4,3505,1,1,52,52,52,52,52,52,52.000000,...,0.0,-1,0.0,2,4480,87616,1,1,32,benign
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50551,30192757,8,5,1375,1065,52,52,759,704,171.875000,...,30000000.0,29993380,0.0,2,4194240,1853440,3,8,32,benign
50552,0,1,0,420,0,420,-1,420,-1,420.000000,...,0.0,-1,0.0,2,0,-1,0,1,0,benign
50553,0,1,0,52,0,52,-1,52,-1,52.000000,...,0.0,-1,0.0,2,5824,-1,0,1,32,adware
50554,33300,1,1,52,52,52,52,52,52,52.000000,...,0.0,-1,0.0,2,87616,13376,1,1,32,benign
50555,51796005,13,10,1098,8687,52,52,259,1390,84.461538,...,51600000.0,51628628,0.0,2,4194240,1853440,9,13,32,adware

In [142]:
#Verificar si hay valores nulos
df.isnull().sum()

duration                   0
total_fpackets             0
total_bpackets             0
total_fpktl                0
total_bpktl                0
                          ..
Init_Win_bytes_backward    0
RRT_samples_clnt           0
Act_data_pkt_forward       0
min_seg_size_forward       0
class                      0
Length: 80, dtype: int64

In [143]:
#verificar si hay valores faltantes
df.isna().sum()

duration                   0
total_fpackets             0
total_bpackets             0
total_fpktl                0
total_bpktl                0
                          ..
Init_Win_bytes_backward    0
RRT_samples_clnt           0
Act_data_pkt_forward       0
min_seg_size_forward       0
class                      0
Length: 80, dtype: int64

In [144]:
print(df['class'].value_counts())
df['class']=df['class'].factorize()[0]
df['class'].value_counts()

class
benign            37727
adware            12449
GeneralMalware      380
Name: count, dtype: int64

class
0    37727
1    12449
2      380
Name: count, dtype: int64

In [145]:
X = df.drop(['class'], axis=1)
y = df['class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40, stratify=y)

In [146]:
from sklearn.ensemble import RandomForestClassifier

clf_rnd = RandomForestClassifier(n_estimators=100,random_state=42)
clf_rnd.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [147]:
y_pred = clf_rnd.predict(X_test)
f1_score (y_test, y_pred, average='weighted')

0.9110773600807113